#!/bin/bash

export _EMPTY_SHELL=0

# must haves
export CLICOLOR=true
export EDITOR="vim"

# handy alias
alias tmux='TERM=xterm-256color tmux'

# all the colors, see profiles/prompt
COLOR_NONE="\[\033[0m\]"
COLOR_GRAY="\[\033[1;30m\]"
COLOR_RED="\[\033[0;31m\]"
COLOR_BLUE="\[\033[0;34m\]"
COLOR_PURPLE="\[\033[00;35m\]"
COLOR_GREEN="\[\033[0;32m\]"
COLOR_YELLOW="\[\033[0;33m\]"

COLOR_LIGHT_RED="\[\033[1;31m\]"
COLOR_LIGHT_BLUE="\[\033[1;34m\]"

COLOR_DARK_GREEN="\[\033[1;36m\]"

# load the profiles
if [ "${#EMPTY_SHELL}" -lt 1 ]
then
  # Keep your personal stuff in here, like secrets, all the secrets
  # I use a truecrypt volume mounted at ~/.mausoleum
  if [ -e "$HOME/.mausoleum/profiles" ]
  then
    for p in $HOME/.mausoleum/profiles/*
    do
      [ -f $p ] && . $p
    done
  fi

  # load secondary "less" secure profiles (in my case another repo)
  if [ -e "$HOME/.cellar/profiles" ]
  then
    for p in $HOME/.cellar/profiles/*
    do
      [ -f $p ] && . $p
    done
  fi

  # load the symphony profiles
  if [ -e "$HOME/.symphony/profiles" ]
  then
    for p in $HOME/.symphony/profiles/*
    do
      [ -f $p ] && . $p
    done
  fi
fi

# Add to .profile or .bashrc as needed
# PROFILE_LOAD="$HOME/.symphony/dotfiles/profile"
#[ -s $PROFILE_LOAD ] && . $PROFILE_LOAD
