#!/bin/bash

wget https://bitbucket.org/pypa/setuptools/downloads/ez_setup.py -O - | python
easy_install pip
pip install virtualenv
pip install virtualenvwrapper
sudo ln -s /usr/local/mysql/lib/libmysqlclient.18.dylib /usr/lib/

