#!/bin/bash

# change these variables as needed
export AWS_KEY_PAIRS="$HOME/.mausoleum/aws/key-pairs"
AWS_USER="ubuntu"

# START example of what goes in key-pairs file
ACCOUNT_LIST="prod dev"
REGION_LIST="us-west-1 us-east-1 eu-west-1"

PROD_US_EAST_1="-i $AWS_PEM_PATH/prod-us-east.pem"
PROD_US_WEST_1="-i $AWS_PEM_PATH/prod-us-east.pem"
PROD_EU_WEST_1="-i $AWS_PEM_PATH/prod-eu-west.pem"

DEV_US_EAST_1="-i $AWS_PEM_PATH/dev-us-east.pem"
DEV_US_WEST_1="-i $AWS_PEM_PATH/dev-us-west.pem"
DEV_EU_WEST_1="-i $AWS_PEM_PATH/dev-eu-west.pem"

PROD_VPC="-i $AWS_PEM_PATH/prod-vpc.pem"
DEV_VPC="-i $AWS_PEM_PATH/dev-vpc.pem"
# END example of key-pairs

if [ -e "$AWS_KEY_PAIRS" ]
then
  . $AWS_KEY_PAIRS
fi

# change as needed for your setup
export AWS_PEM_PATH="$HOME/.mausoleum/ssh"

# normalize the aws tool paths
if [ -e "/usr/local/autoscaling" ]
then
  export AWS_AUTO_SCALING_HOME="/usr/local/autoscaling"
  export PATH="$PATH:${AWS_AUTO_SCALING_HOME}/bin"
fi

if [ -e "/usr/local/rds-cli" ]
then
  export AWS_RDS_HOME="/usr/local/rds-cli"
  export PATH="$PATH:${AWS_RDS_HOME}/bin"
fi

if [ -e "/usr/local/cloudformation" ]
then
export AWS_CLOUDFORMATION_HOME="/usr/local/cloudformation"
  export PATH="$PATH:${AWS_CLOUDFORMATION_HOME}/bin"
fi

if [ -e "/usr/local/iam-cli" ]
then
export AWS_IAM_HOME="/usr/local/iam-cli"
  export PATH="$PATH:${AWS_IAM_HOME}/bin"
fi

if [ -e "/usr/local/ec2-api-tools" ]
then
  export EC2_HOME="/usr/local/ec2-api-tools"
  export PATH="$PATH:${EC2_HOME}/bin"
fi

# for new api tools
export EC2_PRIVATE_KEY="$AWS_PEM_PATH/$USER-private-key.pem"
export EC2_CERT="$AWS_PEM_PATH/$USER-certificate.pem"

# add the aws tools to the path
export PATH="$PATH:${AWS_RDS_HOME}/bin:${AWS_CLOUDFORMATION_HOME}/bin:${EC2_HOME}/bin:${AWS_IAM_HOME}/bin"

# prod ssh aliases
alias ese='ssh $PROD_US_EAST_1 -l $AWS_USER'
alias esw='ssh $PROD_US_WEST_1 -l $AWS_USER'
alias esu='ssh $PROD_EU_WEST_1 -l $AWS_USER'
alias esv='ssh $PROD_VPC -l $AWS_USER'

# dev ssh aliases
alias ede='ssh $DEV_US_EAST_1 -l $AWS_USER'
alias edw='ssh $DEV_US_WEST_1 -l $AWS_USER'
alias edu='ssh $DEV_EU_WEST_1 -l $AWS_USER'
alias edv='ssh $DEV_VPC -l $AWS_USER'

alias ece='scp $PROD_US_EAST_1'
alias ecw='scp $PROD_US_WEST_1'

# Add host names to all commands that ssh
if [ -e "$HOME/.ssh/known_hosts" ]
then
  for c in ssh ese esw esv esu esv ece ecw ede edw edu edv
  do
    if [ -e "$HOME/.ssh/config" ]
    then
      complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\[" | grep -v "%" `; echo `grep "Host " ~/.ssh/config | cut -d " " -f 2`)" $c
    else
      complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\[" | grep -v "%"` )" $c
    fi
  done
fi

complete -W "$ACCOUNT_LIST" aws_account_set
complete -W "$REGION_LIST" aws_region_set

aws_account_unset() {
  unset AWS_ACCOUNT_NAME
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_ACCESS_KEY
  unset AWS_SECRET_KEY

  if [ -e "$HOME/.s3cfg" ]
  then
    rm $HOME/.s3cfg
  fi

  rm $AWS_CREDENTIAL_FILE &> /dev/null
  unset AWS_CREDENTIAL_FILE
}

# functions to set aws account
aws_account_set() {
  # load in your key list
  if [ -e "$AWS_KEY_PAIRS" ]
  then
    . $AWS_KEY_PAIRS
  fi

  name=$1
  export AWS_ACCOUNT_NAME=$name

  eval AWS_ACCESS_KEY_ID=\${$AWS_ACCOUNT_NAME[0]}
  eval AWS_SECRET_ACCESS_KEY=\${$AWS_ACCOUNT_NAME[1]}
  # for the ec2 tools
  eval AWS_ACCESS_KEY=\${$AWS_ACCOUNT_NAME[0]}
  eval AWS_SECRET_KEY=\${$AWS_ACCOUNT_NAME[1]}

  eval account_number=\${$AWS_ACCOUNT_NAME[2]}
  eval default_region=\${$AWS_ACCOUNT_NAME[3]}

  aws_region_set $default_region

  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY

  # for the ec2 tools
  export AWS_ACCESS_KEY
  export AWS_SECRET_KEY

  # for the cloudformation tools
  export AWS_CREDENTIAL_FILE="$AWS_PEM_PATH/cloudformation-credentials-$AWS_ACCOUNT_NAME.pek"

  if [ -h "$HOME/.s3cfg" ]
  then
    rm $HOME/.s3cfg
  fi
  ln -s $HOME/.mausoleum/s3cmd/$AWS_ACCOUNT_NAME $HOME/.s3cfg

cat > $AWS_CREDENTIAL_FILE <<EOF
AWSAccessKeyId=$AWS_ACCESS_KEY_ID
AWSSecretKey=$AWS_SECRET_ACCESS_KEY
EOF
}

aws_account_get() {
  echo $AWS_ACCOUNT_NAME
  echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
}

aws_region_set() {
  region=$1
  export AWS_REGION=$region
  export AWS_DEFAULT_REGION=$region
}

aws_region_get() {
  echo $AWS_REGION
}

aws_region_list() {
  echo $REGION_LIST
}
