#!/bin/bash

if [ "$(uname -s)" == "Darwin" ]
then
  # load the custom profiles
  if [ -e "$HOME/.symphony/profiles/mac" ]
  then
    for p in $HOME/.symphony/profiles/mac/*
    do
      [ -f $p ] && . $p
    done
  fi

  # add the mac bin to the path
  if [ -e "$HOME/.symphony/bin/mac" ]
  then
    export PATH=$HOME/.symphony/bin/mac:$PATH
  fi
fi
