#!/bin/bash

export PROMPT_SHOW_GIT=1

if [ -z $PROMPT_SHRINK_AT ]
then
  export PROMPT_SHRINK_AT=80
fi

prompt_toggle_time() {
  [[ -n "$PROMPT_SHOW_TIME" ]] && unset PROMPT_SHOW_TIME || export PROMPT_SHOW_TIME=1
}

prompt_toggle_git() {
  [[ -n "$PROMPT_SHOW_GIT" ]] && unset PROMPT_SHOW_GIT || export PROMPT_SHOW_GIT=1
}

prompt_toggle_multi() {
  [[ -n "$PROMPT_MULTI_LINE" ]] && unset PROMPT_MULTI_LINE || export PROMPT_MULTI_LINE=1
}


# \072 == :
# for getting the git branch
parse_git_branch() {
  if [ -n "$PROMPT_SHOW_GIT" ]
  then
    BRANCH_NAME=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e "s~* \(.*\)~\1~"`
    if [ "${#BRANCH_NAME}" -gt 0 ]
    then
      if [[ $(tput cols) -lt $PROMPT_SHRINK_AT ]] && [ -z "$PROMPT_MULTI_LINE" ]; then
        short=$(echo $BRANCH_NAME | cut -c1-1)
        echo -e "$COLOR_GRAY\072$COLOR_PURPLE$short$COLOR_NONE"
      else
        echo -e "$COLOR_GRAY\072$COLOR_PURPLE$BRANCH_NAME$COLOR_NONE"
      fi
    fi
  fi
}

print_aws_account() {
  if [ "${#aws_account}" -gt 0 ]
  then
    if [[ $(tput cols) -lt $PROMPT_SHRINK_AT ]] && [ -z "$PROMPT_MULTI_LINE" ]; then
      short=$(echo $aws_account | cut -c1-2)
      echo -e "$COLOR_LIGHT_RED$short$COLOR_NONE"
    else
      echo -e "$COLOR_LIGHT_RED$aws_account$COLOR_GRAY\072$COLOR_PURPLE$AWS_REGION$COLOR_GRAY\072$COLOR_NONE"
    fi
  fi
}

prompt_time() {
  if [ -n "$PROMPT_SHOW_TIME" ]
  then
    echo -e "$COLOR_YELLOW$(date "+%H:%M")$COLOR_GRAY:"
  fi
}

prompt_virtualenv() {
  if [ -n "$VIRTUAL_ENV" ]
  then
    if [[ $(tput cols) -lt $PROMPT_SHRINK_AT ]] && [ -z "$PROMPT_MULTI_LINE" ]; then
      short=$(basename $VIRTUAL_ENV | cut -c1-1)
      echo -e "$COLOR_GREEN$short$COLOR_NONE"
    else
      echo -e "$COLOR_GREEN$(basename $VIRTUAL_ENV)$COLOR_GRAY:"
    fi
  fi
}

prompt_mausoleum() {
  if [[ $(tput cols) -lt $PROMPT_SHRINK_AT ]] && [ -z "$PROMPT_MULTI_LINE" ]; then
    return
  fi

  crypt_mount_count=$(/usr/bin/truecrypt -t -l 2> /dev/null | grep \.mausoleum | wc -l | awk '{print $1}')
  if [ $crypt_mount_count -gt 0 ]
  then
    # radioactive == \xe2\x98\xa2
    echo -e "$COLOR_DARK_GREEN\xe2\x98\xa2$COLOR_GRAY:"
  fi
}

prompt_deps() {
  if [ "$(type -t nodejs_dynamic)" == "function" ]
  then
    nodejs_dynamic
  fi
}

prompt_cdir() {
  if [[ $(tput cols) -lt $PROMPT_SHRINK_AT ]] && [ -z "$PROMPT_MULTI_LINE" ]; then
    # get the current dir, and remove home if it's there
    arr=$(echo "$(pwd | sed "s~$HOME~~")" | tr "/" "\n")
    bn=$(basename `pwd`)
    np=""

    for x in $arr
    do
      if [ "$x" == "$bn" ]; then
        np+=$bn
      else
        np+="$(echo $x | cut -c1-1)/"
      fi
    done

    # return the shortened path
    echo "$COLOR_LIGHT_BLUE$np"
  else
    echo "$COLOR_LIGHT_BLUE\w"
  fi
}

# check if we want a multi line prompt
if [ -n "$PROMPT_MULTI_LINE" ]
then
  PROMPT_COMMAND='PS1="$(prompt_deps)$(prompt_mausoleum)$(print_aws_account)$(prompt_time)$(prompt_virtualenv)$(prompt_cdir)$(parse_git_branch)\n\$(if [[ \$? == 0 ]]; then echo \"$COLOR_GREEN\342\234\223$COLOR_NONE\"; else echo \"$COLOR_RED\342\234\227$COLOR_NONE\"; fi)$COLOR_GRAY\072 $COLOR_NONE";'
else
  PROMPT_COMMAND='PS1="$(prompt_deps)$(prompt_mausoleum)$(print_aws_account)$(prompt_time)$(prompt_virtualenv)$(prompt_cdir)$(parse_git_branch)$COLOR_GRAY\072\$(if [[ \$? == 0 ]]; then echo \"$COLOR_GREEN\342\234\223$COLOR_NONE\"; else echo \"$COLOR_RED\342\234\227$COLOR_NONE\"; fi)$COLOR_GRAY\072 $COLOR_NONE";'
fi

