#!/bin/bash

alias py='python'

# For virtualenvwrapper
if [ -e "/usr/local/bin/virtualenvwrapper.sh" ]
then
  source_file /usr/local/bin/virtualenvwrapper.sh
elif [ -e "/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenvwrapper_lazy.sh" ]
then
  source_file /Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenvwrapper_lazy.sh
fi

export VIRTUALENV_USE_DISTRIBUTE=true
