#!/bin/bash

if [ -e "$HOME/.rvm/bin" ]
then
  export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

if [ -e "$HOME/.rvm/scripts/rvm" ];
then
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
fi
