#!/bin/bash

## Utils and bin locations
# A place for random bash functions and things that add bin locations that aren't
# in a separate file.

# allow vim to work properly for crontab
alias crontab="VIM_CRONTAB=true crontab"

calc(){ awk "BEGIN{ print $* }" ;}

show_colors() { for i in {0..255} ; do     printf "\x1b[38;5;${i}mcolour${i}\n"; done ;}

function aliases() {
  alias | cut -d '=' -f 1 | awk '{print $2}' | sort -u
}

if [ -e "$HOME/.local/.bin" ]
then
  export PATH=$HOME/.local/.bin:$PATH
fi

# load user bin and bash functions
if [ -e "$HOME/.bin" ]
then
  export PATH=$HOME/.bin:$HOME/.bin/symphony:$PATH

  if [ -e "$HOME/.bin/bash" ]
  then
    for f in $HOME/.bin/bash/*; do
      . "$HOME/.bin/bash/$f"
    done
  fi
fi
