set nocompatible                    " get out of vi-compatible mode
set history=1000                    " remember 1000 lines of history
set undolevels=500                  " make sure I can revert back any changes
set clipboard+=unnamed              " share clipboard among vi windows
set ffs=unix,dos,mac                " support the filetypes in this order
set viminfo+=!                      " make sure it can save viminfo
set isk+=_,$,@,%,#,-                " none of these should be word dividers

" Make Diff better
set diffopt=filler
set diffopt+=iwhite

set noswapfile                      " don't make the swap files
set nobackup                        " don't make a backup file
set noautowrite                     " do not save the file automatically if it changes
" if using backup, try these
"set backupdir=$HOME/.vim/backup    " where to put backup files
"set directory=/tmp                 " temp directory (this is where .swp files will be)

set lsp=0                           " space text out (easier to read)
set wildmenu                        " make use of the 'status line' to show command line commands, filenames and more
set lz                              " lazy redraw (don't redraw while running macros)
set backspace=indent,eol,start      " Specify backspacing options
set backspace=2                     " make backspace work normal
set whichwrap+=<,>,[,]              " cursor keys can wrap too. normal mode <,> insert mode [,]
set whichwrap+=h,l                  " enable h and l to wrap lines
set shortmess=atI                   " shortens messages to avoid 'press a key' prompt
set report=0                        " tell me when anything is changed via :

set ch=2                            " Command line height
set ic                              " Show incomplete commands
set showcmd                         " Show Incomplete Commands
set so=5                            " Set the resistance to scroll

"set smartcase                       " Override ignorecase if the search pattern is typed in
set ignorecase                      " Ignore case in pattern searchs
set hlsearch                        " Switch on search pattern highlighting.
set showmatch                       " show matching brackets
set mat=2                           " how many tenths of a second to blick matching bracket
set incsearch                       " do 'highlight' as you type your search phrase
set novisualbell                    " don't blink at me
set noerrorbells                    " don't make a sound

"set formatoptions                   " (default "tcq")
"set formatoptions=tcqrn             " see help deals with formating
set formatoptions-=t                 " don't auto wrap long lines

" set a custom text width (80 for python)
set textwidth=0
" set a wrap margin how many charecters before the edge to wrap at.
set wrapmargin=0

set autoindent                      " autoindent
"set smartindent                     " smartindent
"set cindent                         " stricter rules for C programs

set tabstop=2                       " set the same (tabstop)
set shiftwidth=2                    " set the same (tabstop)
set softtabstop=2                   " set the same (tabstop)
set cino=2                          " set the same (tabstop)
set expandtab                       " Expand Tabs to Whitespace
set nowrap                          " wrap lines
set number                          " show line numbers
set nolist                          " turn off list by default

"" nerd tree settings
" bind ctrl+n to toggle the tree
map <C-n> :NERDTreeToggle<CR>

" tabs
set tabpagemax=15                   " allow 15 tabs to be open

" map alt/meta + [ ] n to tab prev, next and new
" on mac make sure the meta key sends esc for these to work
map - :tabp<CR>
map = :tabn<CR>
" not sure which I like more..
map ^[n :tabnew<CR>
map + :tabnew<CR>

" windows and buffers
set swb=useopen,usetab
set splitbelow                      " send the split down
set splitright                      " send the split right

" misc
map <C-d> :q<CR>

" sets chars to represent tab,trail... when in list mode; try ':set list'
" doesn't always need to be used
set listchars=tab:\|\ ,trail:.,extends:>,precedes:<,eol:$

" sets status line to display file format, type, current char ascii,hex codes, current cursor position
set laststatus=2                    " always show the status line
"set statusline=%f%m%r%h%w\ line\ %l\ of\ %L\ (%p%%)\ col\ %v\ \ \ \%03.3b,0x\%02.2B

" set the status line
" checkout http://vimdoc.sourceforge.net/htmldoc/options.html#'statusline'
set statusline=%n                   " buffer number
set statusline+=\)                  " parentheses separator
set statusline+=%f                  " path to the file
set statusline+=%m%r                " show modified and/or readonly flag
set statusline+=%w                  " show preview flag
set statusline+=%=                  " switch to the right side
set statusline+=%l                  " vurrent line
set statusline+=:                   " colon sep
set statusline+=%v                  " current column
"set statusline+=\%03.3b            " show decimal value of char under cursor
set statusline+=[\%02.2B]           " show hex value of char under cursor
set statusline+=\                   " add a space
set statusline+=%L                  " total lines
set statusline+=(%p%%)              " percent of file


" turn off folding, but when needed, these options are useful
set nofoldenable
"set foldmethod=marker
"set fmr={{{,}}}
"set nofen

" Hide the mouse pointer while typing
set mousehide
set mousem=popup
set mouset=500

" mouse modes, if you're into that (n=normal, v=visual)
"set mouse=nv
"
" enable Pathogen https://github.com/tpope/vim-pathogen
execute pathogen#infect()
" Set nice colors
syntax enable
" choose the dark color scheme
color dark

filetype on                         " detect the type of file
filetype plugin indent on           " load filetype plugins

set magic                           " Change the special charecters for searching
set smd                             " Enable Show Mode on the last line
set notitle                         " Adding this should prevent the 'Thanks for flying with VIM'

" Take care of NumPad
:imap <Esc>Oq 1
:imap <Esc>Or 2
:imap <Esc>Os 3
:imap <Esc>Ot 4
:imap <Esc>Ou 5
:imap <Esc>Ov 6
:imap <Esc>Ow 7
:imap <Esc>Ox 8
:imap <Esc>Oy 9
:imap <Esc>Op 0
:imap <Esc>On .
:imap <Esc>OQ /
:imap <Esc>OR *
:imap <Esc>Ol +
:imap <Esc>OS -

" for Gundo http://sjl.bitbucket.org/gundo.vim/
nnoremap <F8> :GundoToggle<CR>

" for toggling paste
map <F9> :set invpaste<CR>          " Paste Toggle on F9
map ,p :set invpaste<CR>            " Paste Toggle on ,p

" more page up and down goodness
map <C-k> <C-b>
map <C-j> <C-f>

" for perl
"map ,pl :!clear;perl -cw % <CR>

" vi shortcuts
" reload vim config
map ,vr :so $MYVIMRC<CR>

" make shortcuts
map ,mt :!clear;make test<CR>

" grunt shortcuts
map ,gt :!clear;grunt test<CR>

" hide and show comments
map ,sc :highlight Comment term=bold ctermfg=white<CR>
map ,hc :highlight Comment term=bold ctermfg=darkgray<CR>
map ,nc :highlight Comment term=bold ctermfg=black<CR>

nnoremap <F10> :set invhls<CR>:let @/="<C-r><C-w>"<CR>/<BS>

" vim:set ts=2 sw=2 nowrap:
