#!/bin/bash

# With the announcement of Truecrypt no longer being support, migrating to OS specific volumes is required. Will need to research how to enable cross platform copying at some point.

# mount: hdiutil attach $MAUSOLEUM_VOLUME -encryption -readwrite -mountpoint $MAUSOLEUM_MOUNT_PATH
# unmount: hdiutil detach $MAUSOLEUM_MOUNT_PATH
mausoleum() {
  if [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
  then
    echo "usage: "
    return
  fi

  _mausoleum_init

  if [ ! -e "$MAUSOLEUM_VOLUME" ];
  then
    echo "Volume '$MAUSOLEUM_VOLUME' doesn't exist."
    return
  fi

  IS_MOUNTED=$(_mausoleum_mounted)

  if [ "$IS_MOUNTED" -gt 0 ];
  then
    if [ "$1" == "detach" ] || [ "$1" == "umount" ] || [ "$1" == "unmount" ];
    then
      hdiutil detach $MAUSOLEUM_MOUNT_PATH -quiet
    else
      echo "Volume is already mounted."
    fi
  else
    # mount
    hdiutil attach $MAUSOLEUM_VOLUME -encryption -readwrite -mountpoint $MAUSOLEUM_MOUNT_PATH $MAUSOLEUM_OPTS
  fi
}

mausoleum_backup() {
  _mausoleum_init

  IS_MOUNTED=$(_mausoleum_mounted)
  GPG2CLI=$(which gpg2)
  GPGCLI=$(which gpg)

  if [ -e "$GPG2CLI" ];
  then
    GPGCLI=$GPG2CLI
  fi

  if [ ! -e "$GPGCLI" ];
  then
    echo "No GPG cli found."
    return
  fi

  if [ "$IS_MOUNTED" -gt 0 ];
  then
    BACKUP_FILE="$MAUSOLEUM_BACKUP_PATH/mausoleum.$(date +"%Y%m%d.%H%M").tgz.gpg"
    STARTPWD=$(pwd)

    COPYFILE_DISABLE=1
    cd $MAUSOLEUM_MOUNT_PATH && tar -cz * | gpg2 --symmetric --output $BACKUP_FILE
    cd $STARTPWD
    echo "Backed up mausoleum to $BACKUP_FILE"
  else
    echo "Volume must be mounted to perform a backup."
  fi
}

_mausoleum_init() {
  if [ -z "$MAUSOLEUM_OPTS" ];
  then
    MAUSOLEUM_OPTS="-quiet"
  fi

  if [ -z "$MAUSOLEUM_VOLUME" ];
  then
    MAUSOLEUM_VOLUME="$HOME/Documents/crypt.dmg"
  fi

  if [ -z "$MAUSOLEUM_MOUNT_PATH" ];
  then
    MAUSOLEUM_MOUNT_PATH="$HOME/.mausoleum"
  fi

  if [ -z "$MAUSOLEUM_BACKUP_PATH" ];
  then
    MAUSOLEUM_BACKUP_PATH="$HOME/Documents"
  fi
}

_mausoleum_mounted() {
  _mausoleum_init
  RESULT=$(hdiutil info | grep $MAUSOLEUM_MOUNT_PATH | wc -l)
  echo $RESULT
}
