#!/bin/bash

if [ -e "/Applications/Xcode.app/Contents/Developer/" ]
then
  export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer/
elif [ -e "/Applications/Xcode5-DP.app/Contents/Developer" ]
then
  export DEVELOPER_DIR=/Applications/Xcode5-DP.app/Contents/Developer
fi
