#!/bin/bash

alias ls="ls --color=auto"

if [ -e "$(which gnome-open)" ]
then
  alias _open="gnome-open"
elif [ -e "$(which xdg-open)" ]
then
  alias _open="xdg-open"
fi

if [ "$COLORTERM" == "gnome-terminal" ]
then
  export TERM="xterm-256color"
fi
